version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
        - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
        - REDIS_URL=${REDIS_URL}
        - WAIT_TIMES_API_TOKEN=${WAIT_TIMES_API_TOKEN}
    working_dir: /app
    ports:
      - "3000:3000"
      - "3001:3001"
    image: t3-app
    env_file:
      - .env
    # environment:
    #   DATABASE_URL: "file:./db.sqlite"
    #   WAIT_TIMES_API_TOKEN: password
    #   REDIS_URL: redis://redis:6379
    #   NEXT_PUBLIC_WS_URL: ws://localhost:3000
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes